demo_job_1:
   stage: build
   tags:
     - ci
   script:
      - echo Hello World
      - git -C /c/Users/Burudani/Desktop/testFolder_v3 clone https://gitlab.com/rwaki/aws_rwakiterraform.git .
      
      