demo_job_1:
   stage: build
   tags:
     - ci
   script:
     - cd C:\Users\Burudani\Desktop\testFolder_v3
     - dir
     - git clone https://gitlab.com/rwaki/aws_rwakiterraform.git
  


      
      