
stages:
  - build
  - test
  - deploy
  - docs

build_stage:
   stage: build
   tags:
     - ci
   script:
     - cd "C:\Users\Burudani\OneDrive\Documents\OnedriveTestFolder\aws_rwakiterraform"
     - dir
     - git pull https://gitlab.com/rwaki/aws_rwakiterraform.git


test_stage:
   stage: test

   script:
     - echo "This is the Test stage"


deploy_API_stage:
   stage: deploy
  
   script:
     - echo "This is the api-deploy stage"


deploy_CRON_stage:
   stage: deploy
  
   script:
     - echo "This is the cron-deploy stage"


docs_stage:
   stage: docs
   script:
     - echo "This is the docs stage"
     

     