demo_job_1:
   stage: build
   tags:
     - ci
   script:
     - cd "C:\Users\Burudani\OneDrive\Documents\OnedriveTestFolder\aws_rwakiterraform"
     - dir
     - git pull https://gitlab.com/rwaki/aws_rwakiterraform.git