demo_job_1:
   stage: build
   tags:
     - ci
   script:
     - cd C:\Users\Burudani\Documents\mainPythonFolder_v1\builds\d5dVwbmG\0\rwaki
     - dir
     #- echo  pwd

     #- git clone https://gitlab.com/rwaki/aws_rwakiterraform.git
      
      