
stages:
  - build
  - test
  - deploy
  - docs




build_stage:
   stage: build
   tags:
     - ci
   script:
     - cd "C:\Users\Burudani\OneDrive\Documents\OnedriveTestFolder\aws_rwakiterraform"
     - dir
     - git pull https://gitlab.com/rwaki/aws_rwakiterraform.git